"use client";
import { useEffect, useRef } from "react";
import { useAnimate } from "framer-motion";
import PreferenceControl from "./PreferenceControl";
import { useNativeDialog } from "./useNativeDialog";
import { usePortfolio } from "./PortfolioProvider";
export default function Navbar() {
    const { menuOpen, openMenu, closeMenu, motionEnabled } = usePortfolio();
    const menuRef = useRef(null);
    const [, animate] = useAnimate();
    useNativeDialog(menuRef, menuOpen);
    useEffect(() => {
      if (!menuOpen || !motionEnabled) return;
      const animations = [animate(menuRef.current.querySelector('[data-slot~="mobile-menu-shell"]'), { opacity: [0, 1] }, { duration: .24 })];
      menuRef.current.querySelectorAll('nav a').forEach((link, index) => animations.push(animate(link, { opacity: [0, 1], y: [14, 0] }, { duration: .3, delay: (index + 1) * .03, ease: [.22, 1, .36, 1] })));
      return () => animations.forEach(animation => animation.stop());
    }, [animate, menuOpen, motionEnabled]);
    return (<><header data-slot="site-header" className={"h-26 flex items-center justify-between px-[max(var(--gutter),calc((100%_-_1740px)/2_+_var(--gutter)))] [border-bottom:1px_solid_var(--line)] sticky top-0 [background:var(--header)] z-[40] gap-6 max-[800px]:h-20.5 max-[800px]:gap-3.75 max-[560px]:h-19 max-[560px]:gap-2.5 [@media_(min-width:801px)_and_(max-width:1100px)]:gap-4"}>
    <a data-slot="identity" className={"flex items-center gap-3 [font:600_16px/.95_var(--display)] tracking-[-.04em] max-[560px]:gap-2 max-[560px]:text-[13px]"} href="/#home" aria-label="Ronny Das, back to top"><span data-slot="mark personal-mark" className={"w-7.75 h-7.75 [fill:none] [stroke:var(--copper)] [stroke-width:2.8] max-[560px]:w-6.75 max-[560px]:h-6.75 bg-copper [mask:url('/assets/ronny-mark.svg')_center/contain_no-repeat]"} aria-hidden="true"></span><span>RONNY<br />DAS<span data-slot="identity-dot" className={"text-copper"}>.</span></span></a>
    <nav data-slot="desktop-nav" className={"flex gap-8 items-center ml-auto mr-9.5 [&_a]:text-[12px] [&_a]:min-h-11 [&_a]:flex [&_a]:items-center [&_a]:gap-2 [&_a]:relative [&_a:after]:[content:''] [&_a:after]:absolute [&_a:after]:left-0 [&_a:after]:right-0 [&_a:after]:bottom-2.25 [&_a:after]:h-0.25 [&_a:after]:bg-copper [&_a:after]:[transform:scaleX(0)] [&_a:after]:[transform-origin:left] [&_a:after]:[--motion-duration:0.85s] [&_a:after]:[--motion-properties:transform] [&_a:hover:after]:[transform:scaleX(1)] [&_span]:text-[9px] [&_span]:text-muted max-[1100px]:gap-5.75 max-[1100px]:mr-3 max-[800px]:hidden [@media_(min-width:801px)]:[&_span]:text-[12px] [@media_(min-width:801px)_and_(max-width:1100px)]:gap-4 [@media_(min-width:801px)_and_(max-width:1100px)]:mr-0"} data-motion-style="" aria-label="Main navigation"><a href="/#work">Work <span>06</span></a><a href="/#approach">Approach</a><a href="/#about">About</a><a href="/#skills">Skills</a><a href="/#contact">Contact <span aria-hidden="true">↗</span></a></nav>
    <div data-slot="header-controls" className={"flex gap-2 items-center max-[800px]:ml-auto max-[560px]:gap-1.25"}><PreferenceControl kind="motion"/><PreferenceControl kind="theme"/><button id="menu-toggle" data-slot="control menu-control" className={"h-11 min-w-11 hidden justify-center items-center gap-2 p-2.25 [background:transparent] [border:1px_solid_var(--line)] rounded-[50%] [transition:background_.2s,color_.2s] hover:bg-soft [&_svg]:w-4.5 [&_svg]:h-4.5 [&_svg]:[fill:none] [&_svg]:[stroke:currentColor] [&_svg]:[stroke-width:1.4] [&_svg]:[stroke-linecap:round] max-[800px]:flex max-[800px]:rounded-[30px] max-[800px]:text-[10px] max-[800px]:px-3.25 max-[800px]:gap-3 max-[560px]:text-[9px] max-[560px]:p-[9px_11px] max-[560px]:gap-1.5 [&:disabled]:[cursor:default] [&:disabled]:opacity-[.65]"} aria-controls="mobile-nav" aria-expanded={menuOpen} onClick={openMenu}>Menu <svg data-slot="lucide lucide-list" className={"[[data-slot~='menu-control']_&]:[stroke-width:2] [[data-slot~='menu-control']_&]:[stroke-linejoin:round]"} viewBox="0 0 24 24" aria-hidden="true"><path d="M8 6h13M8 12h13M8 18h13M3 6h.01M3 12h.01M3 18h.01"></path></svg></button></div>
  </header><dialog id="mobile-nav" data-slot="mobile-nav" className={"[&:not([open])]:hidden max-[800px]:[dialog&]:fixed max-[800px]:[dialog&]:[inset:0] max-[800px]:[dialog&]:m-0 max-[800px]:[dialog&]:w-full max-[800px]:[dialog&]:h-[100dvh] max-[800px]:[dialog&]:max-w-[none] max-[800px]:[dialog&]:max-h-[none] max-[800px]:[dialog&]:p-0 max-[800px]:[dialog&]:[border:0] max-[800px]:[dialog&]:rounded-none max-[800px]:[dialog&]:bg-bg max-[800px]:[dialog&]:text-ink max-[800px]:[dialog&]:[box-shadow:none] max-[800px]:[dialog&]:[overflow-x:hidden] max-[800px]:[dialog&]:[overflow-y:auto] max-[800px]:[dialog&]:[overscroll-behavior:contain] max-[800px]:[dialog&[open]]:block max-[800px]:[dialog&::backdrop]:bg-bg"} aria-label="Mobile menu" ref={menuRef} onCancel={closeMenu} onClose={closeMenu}>
    <div data-slot="mobile-menu-shell" className={"max-[800px]:min-h-[100%] max-[800px]:flex max-[800px]:flex-col max-[800px]:gap-6 max-[800px]:p-[calc(clamp(18px,3vh,30px)_+_env(safe-area-inset-top,0px))_max(var(--gutter),env(safe-area-inset-right,0px))_calc(clamp(22px,4vh,38px)_+_env(safe-area-inset-bottom,0px))_max(var(--gutter),env(safe-area-inset-left,0px))] [@media_(max-width:800px)_and_(max-height:480px)]:gap-3 [@media_(max-width:800px)_and_(max-height:480px)]:pt-[calc(12px_+_env(safe-area-inset-top,0px))] [@media_(max-width:800px)_and_(max-height:480px)]:pb-[calc(12px_+_env(safe-area-inset-bottom,0px))]"}>
      <div data-slot="mobile-menu-top" className={"max-[800px]:flex max-[800px]:items-center max-[800px]:justify-between max-[800px]:gap-5 max-[800px]:shrink-0"}><a data-slot="identity" className={"flex items-center gap-3 [font:600_16px/.95_var(--display)] tracking-[-.04em] max-[560px]:gap-2 max-[560px]:text-[13px]"} href="/#home" aria-label="Ronny Das, back to top" onClick={closeMenu}><span data-slot="mark personal-mark" className={"w-7.75 h-7.75 [fill:none] [stroke:var(--copper)] [stroke-width:2.8] max-[560px]:w-6.75 max-[560px]:h-6.75 bg-copper [mask:url('/assets/ronny-mark.svg')_center/contain_no-repeat]"} aria-hidden="true"></span><span>RONNY<br />DAS<span data-slot="identity-dot" className={"text-copper"}>.</span></span></a><button id="menu-close" data-slot="control menu-close" className={"h-11 min-w-11 inline-flex justify-center items-center gap-2 p-2.25 [background:transparent] [border:1px_solid_var(--line)] rounded-[50%] [transition:background_.2s,color_.2s] hover:bg-soft [&_svg]:w-4.5 [&_svg]:h-4.5 [&_svg]:[fill:none] [&_svg]:[stroke:currentColor] [&_svg]:[stroke-width:1.4] [&_svg]:[stroke-linecap:round] [&:disabled]:[cursor:default] [&:disabled]:opacity-[.65] max-[800px]:ml-auto max-[800px]:text-[26px] max-[800px]:leading-[1] max-[800px]:[border-color:var(--line)] max-[800px]:shrink-0"} aria-label="Close menu" autoFocus onClick={closeMenu}><span aria-hidden="true">×</span></button></div>
      <nav data-slot="mobile-menu-links" className={"max-[800px]:[flex:1] max-[800px]:flex max-[800px]:flex-col max-[800px]:items-center max-[800px]:justify-center max-[800px]:gap-[clamp(7px,1.8vh,18px)] max-[800px]:p-[16px_0] max-[800px]:text-center max-[800px]:[&_a]:flex max-[800px]:[&_a]:items-center max-[800px]:[&_a]:justify-center max-[800px]:[&_a]:min-h-11 max-[800px]:[&_a]:p-[5px_14px] max-[800px]:[&_a]:[font:500_clamp(32px,5vh,40px)/1.15_var(--display)] max-[800px]:[&_a]:tracking-[-.045em] max-[800px]:[&_a]:[border:0] max-[800px]:[&_a]:text-ink max-[800px]:[&_a]:[transition:color_.2s_ease] max-[800px]:[&_a:hover]:text-copper max-[800px]:[&_a:focus-visible]:[outline-offset:3px] [@media_(max-width:800px)_and_(max-height:480px)]:grid [@media_(max-width:800px)_and_(max-height:480px)]:grid-cols-[repeat(2,minmax(0,1fr))] [@media_(max-width:800px)_and_(max-height:480px)]:[align-content:center] [@media_(max-width:800px)_and_(max-height:480px)]:gap-[7px_26px] [@media_(max-width:800px)_and_(max-height:480px)]:w-[min(100%,430px)] [@media_(max-width:800px)_and_(max-height:480px)]:mx-auto [@media_(max-width:800px)_and_(max-height:480px)]:p-[4px_0] [@media_(max-width:800px)_and_(max-height:480px)]:[&_a]:text-[28px] [@media_(max-width:800px)_and_(max-height:480px)]:[&_a]:p-[3px_10px]"} aria-label="Mobile navigation"><a href="/#work" onClick={closeMenu}>Work<span data-slot="copper" className={"text-copper"}>.</span></a><a href="/#approach" onClick={closeMenu}>Approach<span data-slot="copper" className={"text-copper"}>.</span></a><a href="/#about" onClick={closeMenu}>About<span data-slot="copper" className={"text-copper"}>.</span></a><a href="/#skills" onClick={closeMenu}>Skills<span data-slot="copper" className={"text-copper"}>.</span></a><a href="/#contact" onClick={closeMenu}>Contact<span data-slot="copper" className={"text-copper"}>.</span></a></nav>
      <div data-slot="mobile-menu-bottom" className={"max-[800px]:flex max-[800px]:flex-col max-[800px]:items-center max-[800px]:gap-4.25 max-[800px]:shrink-0 max-[800px]:text-center [@media_(max-width:800px)_and_(max-height:480px)]:gap-2"}><div data-slot="mobile-menu-controls" className={"max-[800px]:flex max-[800px]:items-center max-[800px]:justify-center max-[800px]:gap-3"}><PreferenceControl kind="theme" mobile/><PreferenceControl kind="motion" mobile/></div><a data-slot="mobile-menu-email" className={"max-[800px]:inline-block max-[800px]:p-[6px_3px] max-[800px]:text-[12px] max-[800px]:leading-[1.5] max-[800px]:text-muted max-[800px]:[overflow-wrap:anywhere] max-[800px]:max-w-[100%] max-[800px]:[transition:color_.2s_ease] max-[800px]:hover:text-copper [@media_(max-width:800px)_and_(max-height:480px)]:text-[11px] [@media_(max-width:800px)_and_(max-height:480px)]:py-0.5"} href="mailto:iamronnydas@gmail.com" onClick={closeMenu}>iamronnydas@gmail.com <span aria-hidden="true">↗</span></a></div>
    </div>
  </dialog></>);
}
